name: Link Checker
on:
  pull_request:
    branches:
      - main
      - LinkChecker
  push:
    branches:
      - main
      - LinkChecker
  schedule:
    # run every Sunday at 00:00 UTC
    - cron: '0 0 * * 0'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install linkchecker requests
      - name: amend linkceckerrc to ignore 403 errors
        run: |
            cd
            pwd
            find ~/ -name linkcheckerrc

            cd /home/runner
            pwd
            ls -a

            cd /home/runner/.config
            pwd
            ls -a

            sed -i '/#ignoreerrors=/a ignoreerrors=^http* ^403 Forbidden' /home/runner/linkcheckerrc
      - name: run linkchecker
        run: |
          cd $GITHUB_WORKSPACE/
          nohup python3 -m http.server </dev/null >/dev/null 2>&1 &
          export LOCAL_HOST=$(hostname -i)
          linkchecker --verbose --check-extern http://${LOCAL_HOST}:8000/nav.html
